Fix crash due to formatter return iodata not binary
lexical-lsp/lexical pull request #139
Opened 2023-05-03 16:07 UTC by wingyplus

`Code.format_string!/1` returns iodata but
`Lexical.RemoteControl.CodeMod.Diff.diff/2` expected both `unformatted` and `formatted` to be a binary. This changes fix `formatted` to ensure that it's a binary.

2023-05-04 00:19 UTC, scottming commented
Can you provide an example of reproducing this issue? I'm curious about what situation would return io_data.

2023-05-04 05:29 UTC, wingyplus commented
I found this error when open my work project:

```
[Trace - 12:05:04 PM] Received response 'textDocument/formatting - (3)' in 65ms.
Result: {
  "code": -32603,
  "message": "** (ErlangError) Erlang error: {:exception, :function_clause, [{LXRelease.RemoteControl.CodeMod.Diff, :diff, [\"defmodule RedactedServer.Umbrella.MixProject do\\n  use Mix.Project\\n\\n  @version \\\"version-dev\\\"\\n\\n  def project do\\n    [\\n      apps_path: \\\"apps\\\",\\n      version: @version,\\n      start_permanent: Mix.env() == :prod,\\n      deps: deps(),\\n      aliases: aliases(),\\n      releases: releases(),\\n      dialyzer: [\\n        plt_add_apps: [:mix, :mox],\\n        plt_file: {:no_warn, \\\"priv/plts/dialyzer.plt\\\"}\\n      ],\\n      preferred_cli_env: [\\n        \\\"test.unit\\\": :test,\\n        \\\"test.integration\\\": :test,\\n        \\\"test.external\\\": :test,\\n        \\\"test.all\\\": :test\\n      ]\\n    ]\\n  end\\n\\n  defp deps do\\n    [\\n      {:credo, \\\"~> 1.7.0\\\", only: [:dev, :test], runtime: false},\\n      {:dialyxir, \\\"~> 1.0\\\", only: [:dev], runtime: false},\\n      {:sobelow, \\\"~> 0.8\\\", only: [:dev, :test], runtime: false},\\n      {:junit_formatter, \\\"~> 3.1\\\", only: [:test]},\\n      {:excellent_migrations, \\\"~> 0.1.6\\\", only: [:dev, :test], runtime: false}\\n    ]\\n  end\\n\\n  defp aliases do\\n    [\\n      # run `mix setup` in all child apps\\n      setup: [\\\"cmd mix setup\\\"],\\n      lint: [\\n        \\\"credo\\\",\\n        \\\"sobelow --config --root apps/redacted_server_web/ --exit\\\",\\n        \\\"format --check-formatted\\\"\\n      ],\\n      \\\"lint.fix\\\": [\\\"format\\\"],\\n      \\\"ecto.migrate\\\": \\\"excellent_migrations.migrate\\\",\\n      test: [\\\"ecto.create\\\", \\\"ecto.migrate --quiet\\\", \\\"test\\\"],\\n      \\\"test.unit\\\": [\\\"test --exclude external --exclude integration\\\"],\\n      \\\"test.integration\\\": [\\\"test --only integration\\\"],\\n      \\\"test.external\\\": [\\\"test --only external\\\"],\\n      \\\"test.all\\\": [\\\"test\\\"]\\n    ]\\n  end\\n\\n  defp releases do\\n    [\\n      redacted_server: [\\n        applications: [\\n          redacted_server: :permanent,\\n          redacted_server_web: :permanent,\\n          rabbit_line_pay: :permanent,\\n          redacted_invoice: :permanent\\n        ]\\n      ],\\n      redacted_server_internal_api: [\\n        applications: [\\n          redacted_server: :permanent,\\n          redacted_server_internal_api_web: :permanent\\n        ]\\n      ],\\n      redacted_reconciler: [\\n        applications: [\\n          redacted_server: :permanent,\\n          redacted_reconciler: :permanent,\\n          redacted_reconciler_web: :permanent\\n        ]\\n      ]\\n    ]\\n  end\\nend\\n\", [\"defmodule\", \" \", \"RedactedServer\", \".Umbrella\", \".MixProject\", \" do\", \"\\n  \", \"use\", \" \", \"Mix\", \".Project\", \"\\n\\n  \", \"@version\", \" \", \"\\\"\", \"version-dev\", \"\\\"\", \"\\n\\n  \", \"def\", \" \", \"project\", \" do\", \"\\n    \", \"[\", \"\\n      \", \"apps_path:\", \"\", \" \", \"\\\"\", \"apps\", \"\\\"\", \",\", \"\\n      \", \"version:\", \"\", \" \", \"@\", \"version\", \",\", \"\\n      \", \"start_permanent:\", ...]], [file: 'lib/lexical/remote_control/code_mod/diff.ex', line: 8]}, {LXRelease.RemoteControl.CodeMod.Format, :edits, 2, [file: 'lib/lexical/remote_control/code_mod/format.ex', line: 17]}]}\n    (kernel 8.5.3) erpc.erl:702: :erpc.call/5\n    (server 0.1.0) lib/lexical/server/provider/handlers/formatting.ex:13: LXRelease.Server.Provider.Handlers.Formatting.handle/2\n    (server 0.1.0) lib/lexical/server/provider/queue.ex:100: anonymous fn/2 in LXRelease.Server.Provider.Queue.State.as_task/2\n    (elixir 1.14.4) lib/task/supervised.ex:89: Task.Supervised.invoke_mfa/2\n    (elixir 1.14.4) lib/task/supervised.ex:34: Task.Supervised.reply/4\n    (stdlib 4.2) proc_lib.erl:240: :proc_lib.init_p_do_apply/3\n"
}
```

The issue happen when open `mix.exs` and running formatting through LSP (In my case, I use emacs-lsp). After read the source, I guess that it might fallback to `Code.format_string!` that return iodata. I'm not sure why it fallback to that path. :(

2023-05-04 06:51 UTC, scottming commented
Have you tried the #111 branch and replaced the ProjectNode `def handle_info({_port` function with 

```elixir
  @impl true
  def handle_info({_port, {:data, message}}, state) do
    message = message |> IO.iodata_to_binary() |> String.trim()
    Logger.info("Port: #{message}")
    {:noreply, state}
  end
```
And use `mix release lexical --overwrite` to release a new version and check the `.lexical/lexical.log`.

I still suspect that this is due to incomplete compilation rather than format.

2023-05-04 13:46 UTC, scohen requested changes

2023-05-04 17:41 UTC, wingyplus commented
@scottming Unfortunately, I didn't see any log from `lexical.log`. I may something mistake. But I found the error like this through the lexical stderr:

```
Error while loading project :redacted_server at /Users/thanabodee/src/redacted_server/apps/redacted_server
```

I think it problably the cause why it's fallback to `Code.format_string!` path. 🙇

2023-05-04 17:52 UTC, wingyplus commented on apps/remote_control/lib/lexical/remote_control/code_mod/format.ex
> +      edits = Diff.diff(unformatted, IO.iodata_to_binary(formatted))
Fixed. And I add `\n` at the end make it same as `Mix.Tasks.Format` does.

2023-05-05 04:30 UTC, scohen approved these changes

2023-05-05 04:30 UTC, merged

2023-05-05 05:18 UTC, scottming commented
> , I didn't see any log from lexical.log
@wingyplus did you use `MIX_ENV=prod mix release ...` to release `lexcial`?

2023-05-05 09:51 UTC, wingyplus commented
> > , I didn't see any log from lexical.log
> 
> @wingyplus did you use `MIX_ENV=prod mix release ...` to release `lexcial`?

@scottming yes. But it didn’t work. The patch #140 suppose to work?

I guess that it probably cause by my project requires to have some env variables during compile but it missing somehow. I will check when I’m on my laptops.

2023-05-05 09:54 UTC, scottming commented
Yes, logs were not generated for PROD releases before #140 , so I enabled it.

2023-05-05 17:24 UTC, wingyplus commented
@scottming Trying with #111 and patch #140 and this patch:

```lexical
diff --git a/apps/remote_control/lib/lexical/remote_control/project_node.ex b/apps/remote_control/lib/lexical/remote_control/project_node.ex
index 7d97ce6..be410f3 100644
--- a/apps/remote_control/lib/lexical/remote_control/project_node.ex
+++ b/apps/remote_control/lib/lexical/remote_control/project_node.ex
@@ -206,7 +206,9 @@ defmodule Lexical.RemoteControl.ProjectNode do
   end

   @impl true
-  def handle_info({_port, {:data, _message}}, %State{} = state) do
+  def handle_info({_port, {:data, message}}, %State{} = state) do
+    message = message |> IO.iodata_to_binary() |> String.trim()
+    Logger.info("Port: #{message}")
     {:noreply, state}
   end
```

The result from lexical.log:

```
Start Call: Lexical.Server.Project.Node.start_link(%Lexical.Project{root_uri: "file:///Users/thanabodee/src/redacted/redacted_server", mix_exs_uri: "file:///Users/thanabodee/src/redacted/redacted_server/mix.exs", mix_project?: true, mix_env: nil, mix_target: nil, env_variables: %{}})
Restart: :permanent
Shutdown: 5000
Type: :worker
00:19:32.797 [info] Lexical Initialized
00:19:32.798 [info] opened file:///Users/thanabodee/src/redacted/redacted_server/mix.exs
00:19:32.937 [info] Port: 00:19:32.937 [info] initial build complete
00:19:33.012 [info] unhandled request $/cancelRequest
00:19:33.113 [info] Compiled redacted_server in 174 ms
00:19:33.113 [error] Invalid diagnostic: {:exception, {%Mix.Error{message: "Trying to load RedactedServer.Umbrella.MixProject from \"/Users/thanabodee/src/redacted_server/mix.exs\" but another project with the same name was already defined at \"/Users/thanabodee/src/redacted/redacted_server/mix.exs\"", mix: 1}, [{Mix, :raise, 2, [file: 'lib/mix.ex', line: 513]}, {Mix.Project, :load_project, 2, [file: 'lib/mix/project.ex', line: 785]}, {Mix.Project, :in_project, 4, [file: 'lib/mix/project.ex', line: 389]}, {File, :cd!, 2, [file: 'lib/file.ex', line: 1607]}, {Mix.Dep, :in_dependency, 3, [file: 'lib/mix/dep.ex', line: 271]}, {Mix.Dep.Loader, :load, 2, [file: 'lib/mix/dep/loader.ex', line: 95]}, {Mix.Dep.Converger, :"-all/9-fun-0-", 4, [file: 'lib/mix/dep/converger.ex', line: 219]}, {Mix.Dep.Converger, :all, 9, [file: 'lib/mix/dep/converger.ex', line: 215]}]}, [{Mix, :raise, 2, [file: 'lib/mix.ex', line: 513]}, {Mix.Project, :load_project, 2, [file: 'lib/mix/project.ex', line: 785]}, {Mix.Project, :in_project, 4, [file: 'lib/mix/project.ex', line: 389]}, {File, :cd!, 2, [file: 'lib/file.ex', line: 1607]}, {Mix.Dep, :in_dependency, 3, [file: 'lib/mix/dep.ex', line: 271]}, {Mix.Dep.Loader, :load, 2, [file: 'lib/mix/dep/loader.ex', line: 95]}, {Mix.Dep.Converger, :"-all/9-fun-0-", 4, [file: 'lib/mix/dep/converger.ex', line: 219]}, {Mix.Dep.Converger, :all, 9, [file: 'lib/mix/dep/converger.ex', line: 215]}]}
```

2023-05-05 17:25 UTC, wingyplus commented
Probably because of `Mix.Error` in diagnostic?

2023-05-05 23:32 UTC, scottming commented
> Probably because of Mix.Error in diagnostic?
nope

This error is caused by multiple instances of the `mix` command being used simultaneously. Currently, Lexical does not support multiple editors opening the same project.

Additionally, it seems that your patched version did not take effect. First, you must use 

```sh
$ rm -rf _build deps .lexical && mix deps.get       
```

in the Lexical project and then release it with `mix release lexical --overwrite`. 

Next, confirm that your editor is using a command path similar to this

```
# neovim
 	cmd:               /Users/<user>/Code/lexical/_build/dev/rel/lexical/start_lexical.sh
```

if you're using vscode, I think the path override should be: `/Users/<user>/Code/lexical/_build/dev/rel/lexical/`

Under normal circumstances, you should be able to see some info logs that start with "Port: ".

like

```elixir
Type: :worker
07:31:31.739 [info] Lexical Initialized
07:31:31.739 [info] opened file:///Users/scottming/Code/lexical/apps/remote_control/lib/lexical/remote_control/project_node.ex
07:31:32.775 [info] Port: Resolving Hex dependencies...
07:31:32.823 [info] Port: Resolution completed in 0.047s
07:31:32.826 [info] Port: Unchanged:
  bunt 0.2.1
  credo 1.7.0
  dialyxir 1.2.0
  earmark_parser 1.4.31
  erlex 0.2.6
07:31:32.826 [info] Port: ex_doc 0.29.2
  file_system 0.2.10
07:31:32.826 [info] Port: jason 1.4.0
07:31:32.826 [info] Port: logger_file_backend 0.0.13
07:31:32.826 [info] Port: makeup 1.1.0
  makeup_elixir 0.16.0
  makeup_erlang 0.1.1
07:31:32.826 [info] Port: nimble_parsec 1.2.3
07:31:32.826 [info] Port: patch 0.12.0
```

2023-05-06 00:21 UTC, scottming commented
Furthermore, if no useful information can be found in the end, deleting `.lexical` under the project may help. However, we do not recommend users do so as it is not a good way to fix dependency issues🤣

2023-05-06 04:40 UTC, wingyplus commented
@scottming I found a warning when deleting `.lexical`, `_build`, `deps` and refetch with `mix deps.get` before open editor to start LSP:

```
# lexical.log
11:28:05.773 [info] Port: 11:28:05.773 [info] initial build complete
11:28:06.028 [info] Port: 11:28:06.027 [warning] Could not connect to hex.pm, dependencies will not be fetched
```

I realize that I have git dependencies in my project, it's internal library. So I change it to local path, the warning is gone. But the LSP still not build unlike open lexical project. T_T

2023-05-06 04:49 UTC, wingyplus commented
And I still found the `Invalid diagnostic` error even I restart the laptops. Not sure if I encounter #141 bug?

2023-05-06 05:02 UTC, scottming commented
No need to restart the laptops :), and #141 is mainly an enhancement rather than a bug.

> And I still found the Invalid diagnostic error even I restart the laptops. Not sure if I encounter https://github.com/lexical-lsp/lexical/issues/141 bug?

Unless there is a public repository and clear reproduction steps, I have no idea now. 

of course, you can try #135 , that feature should be stable now.

2023-05-06 06:09 UTC, wingyplus commented
Thank you. I’ve no idea also why it’s not working. 😂


BTW, thanks for your help. 🙇‍♂️