Fix normalize_path on Windows
lexical-lsp/lexical pull request #373
Opened 2023-09-17 05:09 UTC by CharlesOkwuagwu

This fixes `normalize_path ` on Windows.

2023-09-17 12:16 UTC, zachallaun requested changes
Thank you for trying to address this!

There's a compilation error in this PR (`origin` doesn't exist). I'm also wondering if we can use CI to try to run `mix package` in a windows environment and make sure it succeeds.

2023-09-17 12:16 UTC, zachallaun commented on apps/server/lib/mix/tasks/package.ex
> -
Please keep this newline.

2023-09-17 12:16 UTC, zachallaun commented on apps/server/lib/mix/tasks/package.ex
> +            origin
```suggestion
            orig
```

2023-09-17 12:16 UTC, zachallaun commented on apps/server/lib/mix/tasks/package.ex
> +           _ ->
```suggestion

          _ ->
```

2023-09-17 22:22 UTC, CharlesOkwuagwu commented on apps/server/lib/mix/tasks/package.ex
> -
Cool. I guess we can close this then.

2023-09-18 20:36 UTC, scohen commented
What was the bug? There's no description in the PR, and it looks to me like this won't handle relative paths on windows.

2023-10-05 15:35 UTC, scohen commented
I'm closing this, as I don't think it will have any meaningful effect on whether or not lexical runs on windows.

2023-10-05 15:35 UTC, closed without merging