Move `entity` module to `remote_control` app
lexical-lsp/lexical pull request #406
Opened 2023-10-12 06:27 UTC by scottming

`resolve` does not depend on the project startup.

After moving it, firstly, it makes our testing more convenient, and secondly, it allows other modules of remote_control to reuse the resolve function of the entity.

2023-10-12 13:53 UTC, zachallaun approved these changes
Nice!

2023-10-12 15:44 UTC, scohen requested changes
It is strange for something in remote control to call RemoteControl.API (this happens in Entity.definition, for example)
The stuff in there needs to be extracted and moved into the providers in the `server` app.

2023-10-13 10:13 UTC, scottming commented
> It is strange for something in remote control to call RemoteControl.API (this happens in Entity.definition, for example)
The stuff in there needs to be extracted and moved into the providers in the server app.

Yes, it does seem a bit strange.

In my new commit, I moved this part to the `definition.ex` file.

Additionally, I kept the logic for parsing ElixirSense results in there because once we can replace `ElixirSense,` this part of the logic will be unnecessary.

2023-10-13 21:16 UTC, scohen approved these changes

2023-10-13 23:42 UTC, merged