handle other cases where project node goes down
lexical-lsp/lexical pull request #790
Opened 2024-07-10 02:08 UTC by Moosieus

Doesn't fix #788, but should at least have it restart properly.

To fix the root cause, the project itself needs to be diagnosed.

2024-07-10 02:19 UTC, scohen commented on apps/remote_control/lib/lexical/remote_control/project_node.ex
> +        end
```suggestion
        if is_tuple(state.stopped_by) do
          GenServer.reply(state.stopped_by, :ok)
        end
        {:shutdown, %{state | status: :stopped}}
```

2024-07-10 02:19 UTC, scohen commented on apps/remote_control/lib/lexical/remote_control/project_node.ex
> +        if state.stopped_by !== nil do
```suggestion
        if is_tuple(state.stopped_by) do
```

2024-07-10 02:20 UTC, scohen approved these changes

2024-07-10 08:24 UTC, dvic reviewed
Should the if check also be added to https://github.com/lexical-lsp/lexical/pull/790/files#diff-e7c896fbe6494e8c68eca1ba1506ee75ae0a4e6908b30b65e37964d7c9d7d163R215?

2024-07-10 15:47 UTC, scohen commented
> Should the if check also be added to

Yes, it should. @Moosieus ☝️

2024-07-10 15:48 UTC, scohen requested changes
Also fix the other instance of this reply, maybe make a function called `maybe_reply_to_stopper`

2024-07-11 15:36 UTC, scohen approved these changes

2024-07-11 21:05 UTC, merged